import esbuild from "esbuild";
import process from "process";
import builtins from "module";
import { copyFileSync, mkdirSync, existsSync } from "fs";

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');
const outdir = 'dist';

// Ensure dist/ directory exists
if (!existsSync(outdir)) {
	mkdirSync(outdir, { recursive: true });
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins.builtinModules,
	],
	format: 'cjs',
	target: 'es2022',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: `${outdir}/main.js`,
});

if (prod) {
	await context.rebuild();

	// Copy required plugin files to dist/
	copyFileSync('manifest.json', `${outdir}/manifest.json`);
	if (existsSync('styles.css')) {
		copyFileSync('styles.css', `${outdir}/styles.css`);
	}

	console.log('✅ Build complete! Files are in dist/');
	process.exit(0);
} else {
	await context.watch();
}
